version: '3.1'

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    expose:
      - '8086'
    volumes:
      - influxdb:/var/lib/influxdb

  influxdb_cli:
    image: influxdb
    container_name: incluxdb_cli
    entrypoint: influx setup --bucket ${IDB_BUCKET_NAME} -t ${IDB_TOKEN} -o ${IDB_ORG} --username=${IDB_USERNAME} --password=${IDB_PASSWORD} --host=${IDB_HOST} -f
    restart: on-failure:10
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - influxdb_cli
    expose:
      - '3000'
    volumes:
      - grafana:/var/lib/grafana
      - ./deployment/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./deployment/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./deployment/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - IDB_BUCKET_NAME=${IDB_BUCKET_NAME}
      - IDB_TOKEN=${IDB_TOKEN}
      - IDB_ORG=${IDB_ORG}
      - IDB_URL=${IDB_HOST}

  act-app:
    image: act-app
    container_name: assetto-corsa-telemetry-forwarder
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GAME_SERVER_IP_ADDRESS=${GAME_SERVER_IP_ADDRESS}
      - IDB_BUCKET_NAME=${IDB_BUCKET_NAME}
      - IDB_TOKEN=${IDB_TOKEN}
      - IDB_ORG=${IDB_ORG}
      - IDB_URL=${IDB_HOST}
    depends_on:
      - grafana

volumes:
  influxdb:
  grafana: