{
 "title": "Telemetry Dashboard",
 "description": "Dashboard exposes telemetry data from Assetto Corsa",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wheels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Suspension Height",
     "type": "table",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"suspensionHeight\"\n  )\n  |> last()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Dynamic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Speed Dashboard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"speed at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPM Dashboard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"engine RPM at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brake Throttle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"brake at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clutch Throttle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"clutch at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Throttle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"gas at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"acceleration at current time\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ABS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isAbsEnabled\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ABS Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isAbsInAction\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Limiter On",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isEngineLimiterOn\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lap Completeness",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"lap completeness\"\n  )\n  |> aggregateWindow(every: 1s, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traction Control",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isTcEnabled\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traction Control Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isTcInAction\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Pit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"assetto-corsa-telemetry\")\n  |> range(start:-1m)\n  |> filter(fn:(r) =>\n    r._measurement == \"isInPit\"\n  )\n  |> map(fn: (r) => ({ r with _value: if r._value == true then \"ON\" else \"OFF\"}))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}