apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: $IDB_URL
    isDefault: true
    secureJsonData:
      token: $IDB_TOKEN
    jsonData:
      version: Flux
      organization: $IDB_ORG
      defaultBucket: $IDB_BUCKET_NAME
      tlsSkipVerify: true