name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github-act4j", "name": "github-act4j", "url": "https://maven.pkg.github.com/iimetra/assetto-corsa-telemetry-4j", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{"id": "github", "username": "iimetra", "password": "${{ secrets.PASS }}"}]'
      - run: |
          cat ~/.m2/settings.xml
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify